SELECT 
	O.NAME '資料表', 
	MAX(C.ORDINAL_POSITION) '欄位數', 
	MAX(P.ROWS) '資料總筆數' 
FROM SYS.SYSOBJECTS O
INNER JOIN SYS.PARTITIONS P ON O.ID = P.OBJECT_ID
INNER JOIN INFORMATION_SCHEMA.COLUMNS C ON O.NAME = C.TABLE_NAME
WHERE 
	O.NAME LIKE 'SKS%' 
GROUP BY O.NAME
